message("\n===== Running pipeline =====\n")
message("\n===== OMICS =====\n")
message("\n===== Step 1: Extracting APOE status from genomics data =====\n")
source( paste0(here(), "/scripts/1.apoe_status_extraction.R"))
message("\n===== Step 2: Running ML/stats on somascan data =====\n")
source(paste0(here(), "/scripts/2.somascan.R"))
message("\n===== Step 3: Running ML/stats on transcriptomics data =====\n")
source(paste0(here(), "/scripts/3.transcriptomics.R"))
message("\n===== Step 4: Running ML/stats on MassSpec data =====\n")
source(paste0(here(), "/scripts/4.proteomics.R"))
message("\n===== Step 5: Running ML/stats on epigenomics data =====\n")
source(paste0(here(), "/scripts/5.epigenomics.R"))
message("\n===== Somalogic Longitudinal =====\n")
message("\n===== ALSFRS =====\n")
source(paste0(here(), "/scripts/6.ALSFRS.R"))
message("\n===== CBS =====\n")
source(paste0(here(), "/scripts/7.CBS.R"))
message("\n===== LNS =====\n")
source(paste0(here(), "/scripts/8.LNS.R"))
message("\n===== Job Done =====\n")